version: '3.4'

services:
  mongodb:
    image: mongo:6-jammy
    #ports:
      #- "27017:27017"
    volumes:
      - ./mongodb-data:/data/db
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MONGO_INITDB_DATABASE=app
      - MONGO_INITDB_ROOT_USERNAME=app
      - MONGO_INITDB_ROOT_PASSWORD=app
    networks:
      - backend

  nginx:
    image: nginx:1.13.10-alpine
    ports:
      - "5000:80"
    volumes:
      - ./nginx/default/:/etc/nginx/conf.d
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - app
    networks:
      - frontend

  app:
    build: .
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /etc/localtime:/etc/localtime:ro
    working_dir: "/usr/src/app"
    command: python run.bjoern.py
    restart: on-failure:5
    networks:
      - frontend
      - backend
    #env_file:
      #- .env
    environment:
      - LANG=C.UTF-8
      - APP_ENVIRONMENT=production

networks:
  frontend:
    driver: bridge #or overlay in swarm mode
  backend:
    driver: bridge #or overlay in swarm mode
