version: '3.4'

services:
  mongodb:
    image: aashreys/mongo-auth:latest
    #ports:
      #- "27017:27017"
    volumes:
      - ./mongodb-data:/data/db
      - /etc/localtime:/etc/localtime:ro
    environment:
      - AUTH=yes
      - MONGODB_ADMIN_USER=admin
      - MONGODB_ADMIN_PASS=admin
      - MONGODB_APPLICATION_DATABASE=app
      - MONGODB_APPLICATION_USER=app
      - MONGODB_APPLICATION_PASS=app

  nginx:
    image: nginx:1.13.10-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default-ssl/:/etc/nginx/conf.d
      - ./letsencrypt/certs/:/certs/
      - ./letsencrypt/challenge/:/var/www/letsencrypt/challenge/
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - app
      - letsencrypt

  letsencrypt:
    build: letsencrypt
    #entrypoint: certbot-wrapper.sh
    command: /bin/true
    volumes:
      - ./letsencrypt/certbot-wrapper.sh:/usr/bin/certbot-wrapper.sh
      - ./letsencrypt/certs/:/etc/letsencrypt/certs/
      - ./letsencrypt/challenge/:/etc/letsencrypt/challenge/
      - ./letsencrypt/accounts/:/etc/letsencrypt/accounts/
    #env_file:
      #- .env
    #environment:
      #- APP_DOMAIN=${APP_DOMAIN}

  app:
    build: .
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /etc/localtime:/etc/localtime:ro
    working_dir: "/usr/src/app"
    command: gunicorn -w 2 -b :8000 app:app
    restart: on-failure:5
    #env_file:
      #- .env
    environment:
      - LANG=C.UTF-8
      - APP_ENVIRONMENT=production
