version: '3.4'

services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    volumes:
      #- ./mongodb-data:/data/db
      - mongodb-data:/data/db #windows workaround
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MONGO_INITDB_DATABASE=app
      - MONGO_INITDB_ROOT_USERNAME=app
      - MONGO_INITDB_ROOT_PASSWORD=app

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /etc/localtime:/etc/localtime:ro
    working_dir: "/usr/src/app"
    restart: on-failure:5
    #env_file:
      #- .env
    environment:
      - LANG=C.UTF-8
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
      - FLASK_RUN_HOST=0.0.0.0
      - TEMPLATES_AUTO_RELOAD='True'
      - APP_ENVIRONMENT=development

volumes:
  mongodb-data:
