version: '3.4'

services:
  mongodb:
    image: aashreys/mongo-auth:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db
    environment:
      - AUTH=yes
      - MONGODB_ADMIN_USER=admin
      - MONGODB_ADMIN_PASS=admin
      - MONGODB_APPLICATION_DATABASE=hello-world
      - MONGODB_APPLICATION_USER=hello-world
      - MONGODB_APPLICATION_PASS=hello-world

  nginx:
    image: nginx:1.13.10-alpine
    ports:
      - "5000:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - hello-world

  hello-world:
    build: .
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
    working_dir: "/usr/src/app"
    restart: on-failure:5
    command: python run.cherry.py
    environment:
      - LANG=C.UTF-8
